### ISSUE TITLE
Inputdata exceeded threshold of 105906176

### ISSUE THREAD

**Issue by artur-kacen** [difi/oxalis#229]
Hello,

We where not able to send huge file (127 MB) due to restriction of 106 MB:
  Util.intoBuffer(inputStream, 101L * 1024 * 1024);  from TransmissionRequestBuilder.savePayLoad()

How should we handle this kind of files if Oxalis is not allowing to parse them?

/Artur

**Comment by klakegg** [comment]
Files above 100MB are currently not subject for OpenPEPPOL.

**Comment by Tickstar** [comment]
@klakegg, please provide a link to documentation or specs where this limit is stated. We are experienceing an increase in transfers of 50+ MB catalogues in the PEPPOL network. Hence, it would be good to re-evaluate file size limits introduced years ago.

**Comment by klakegg** [comment]
I think the Norwegian PEPPOL Authority is the only autority having said anything about this, and 100MB is set as a cap to make running inbound access point services maintainable when it comes to handling local resources and as fundament for scaling.

**Comment by steinarcook** [comment]
I think this is an issue for OpenPEPPOL to make a decision on.

On 20 October 2015 at 11:38, Erlend Klakegg Bergheim <
notifications@github.com> wrote:

> I think the Norwegian PEPPOL Authority is the only autority having said
> anything about this, and 100MB is set as a cap to make running inbound
> access point services maintainable when it comes to handling local
> resources and as fundament for scaling.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/difi/oxalis/issues/229#issuecomment-149496138>.
>



-- 
Steinar Overbeck Cook

**Comment by monze** [comment]
Just a comment
At least put the max size in a configuration file.
If/when Peppol or Norwegian PEPPOL Authority deside to raise the max size, no providers can use the new max size, before they have update their current version off Oxalis (because it is hard-code). If it is in a config file, a configuration can resolve the problem.

Also, even if the Norwegian PEPPOL Authority don't change the max zsize, the Danish PEPPOL Authority could decide that the max side for danish National format is 200mb... So other users of Oxalis should have the possibility to change the max size.

**Comment by steinarcook** [comment]
I think this is an excellent idea and I support it.

**Comment by Tickstar** [comment]
PEPPOL is about cross border interoperability. It would be the wrong path to make it the choice of individual PEPPOL authorities to decide maximum file sizes in their respective domains/regions. We honestly don't understand the reason for this.
