### ISSUE TITLE
Galaxygw issue: The Oxalis server does not seem to be running at galaxygw.com

### ISSUE THREAD

**Issue by simakas** [difi/oxalis#243]
I cant seem to send to Galaxy type AP, anyone having similar issue? Oxalis 3.0.2, got 7 such cases in the system, all for Galaxy:

```
DEBUG [eu.peppol.as2.As2DispositionNotificationOptions] Inspecting signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1
2015-12-15 09:14:03,148 DEBUG [eu.peppol.outbound.transmission.As2MessageSender] Sending AS2 from 9908:999026966 to 9908:948554062 at https://ibistic-ap.galaxygw.com:12181/ap/as2 type urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0:extended:urn:www.difi.no:ehf:faktura:ver2.0::2.1 Message failed : The Oxalis server does not seem to be running at https://ibistic-ap.galaxygw.com:12181/ap/as2 | OERRSTREAM:
```

```
DEBUG [eu.peppol.as2.As2DispositionNotificationOptions] Inspecting signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1 2015-12-01 08:54:07,314 DEBUG [eu.peppol.outbound.transmission.As2MessageSender] Sending AS2 from 9908:982519985 to 9908:913547853 at https://palette-ap.galaxygw.com:12381/ap/as2 type urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0:extended:urn:www.difi.no:ehf:faktura:ver2.0::2.1 Message failed : The Oxalis server does not seem to be running at https://palette-ap.galaxygw.com:12381/ap/as2 | OERRSTREAM:
```

**Comment by Tickstar** [comment]
The AP's hosted on Galaxy GW do not run on Oxalis. 
Does your firewall allow traffic on the port numbers used by Galaxy GW?

**Comment by simakas** [comment]
Message is misleading alright, probably standard. I cant really tell which ports Galaxy is connecting back, is there a standard port it uses? I see ports destination AP's are running on and connection is established from my side, so im not expecting a response to any random port on my side..

**Comment by Tickstar** [comment]
In this particular case port number 12181 is used but we use ports ranging from 10181 and up. 
Can you access https://ibistic-ap.galaxygw.com:12181/ap/as2 with your internet browser from where you are? Please use IE since Chrome returns a Diffie-Hellman error.

**Comment by christian-andersson** [comment]
Does your Firewall allow you to connect to the galaxygw ports? according to the above exceptions..
ibistic-ap.galaxygw.com uses port 12181
palette-ap.galaxygw.com uses port 12381

Personally I think galaxygw is doing things wrong and not using the standard https port of 443...
because there might be many accesspoints that is using wirewalls that is restricting outgoing connections.

also the encryption handler on these sites are OLD and uses weak deprecated key handling..

for example if I connect to these sites using chrome I get the below SSL errors..

ERR_SSL_WEAK_SERVER_EPHEMERAL_DH_KEY

this means that your java version might not allow you to connect to these sites..

**Comment by simakas** [comment]
I can, but my server cant :) looks like my service provider is blocking all non-standard outgoing ports, will have a word with them, but I agree with @christian-andersson - a default port would cause less headache for everybody.
And Diffie-hellman error is not AP related its SHA1 to SHA2 requirement change for SSLs which is enforced by Chrome. This is not a problem - working fine if you got SHA2 cert or a different browser.

**Comment by christian-andersson** [comment]
No, it is not AP related, it is http-server related, and the server should be updated.

and with newer versions of java, you might get errors connecting to a site with this problem..  

so yes, it is not jsut to say that use another browser, the problem is that the site have not updated it's security, and therefore should no longer be considered safe...

**Comment by simakas** [comment]
confirming its a providers network setup issue, blocking outgoing traffic on non-standard ports.

**Comment by Tickstar** [comment]
We have now patched all AP's of Galaxy Gateway to fix the Logjam vulnerability a.k.a "weak ephemeral Diffie-Hellman public key" issue,
