### ISSUE TITLE
Is SMP Lookup Changes in Oxalis 4.0.2 TEST Mode 

### ISSUE THREAD

**Issue by VijayaKumar2** [difi/oxalis#350]
Currently we are registering the identifier into SMP and which are with the following URL,

http://B-bd02140a4d95d537336ce345297d41d9.iso6523-actorid-upis.**edelivery.tech.ec.europa.eu**/iso6523-actorid-upis%3A%3A9918%3A999/services/busdox-docid-qns%3A%3Aurn%3Aoasis%3Anames%3Aspecification%3Aubl%3Aschema%3Axsd%3AInvoice-2%3A%3AInvoice%23%23urn%3Awww.cenbii.eu%3Atransaction%3Abiicoretrdm010%3Aver1.0%3A%23urn%3Awww.peppol.eu%3Abis%3Apeppol4a%3Aver1.0%23urn%3Awww.simplerinvoicing.org%3Asi-ubl%3Ainvoice%3Aver1.0.x%3A%3A2.0

But when we are sending the document from the Oxalis 4.0.2 - Outbound component with PEPPOL - TEST Certificate, getting the following exception saying, identifier not available in SMP, when I was debugging getting the difference in the HOST name 

gakd6jxeurrdrxqrkknibgowzra2iqqjnakxsnoofzkzmo6rfvyq.iso6523-actorid-upis.**acc.edelivery.tech.ec.europa.eu**

Which is different from the registered one, when I am changing the host name, i am getting the details, but again in the API, validating with the certificate of TEST Mode and getting failed.

Could any one can help on this.

Thanks,
Vijay

**Comment by MarcoDeTiege** [comment]
Hello Vijay,

Oxalis detects in which mode it is running depending on the certificate you have configured for use. If you are using a PEPPOL TEST certificate, Oxalis will run in test mode. This means it will use SMK for  lookups instead of SML.
SMK queries result in the acc.edelivery.tech.ec.europa.eu domain, whereas SML queries result in the regular edelivery.tech.ec.europa.eu domain. 
If you want to send documents in TEST mode, please make sure you've registered your recipient in SMK.

**Comment by VijayaKumar2** [comment]
Thanks...
