### ISSUE TITLE
Documentation for persistence of messages in a database

### ISSUE THREAD

**Issue by rzvpopescu22** [difi/oxalis#387]
Hi!
Is there some documentation on modifications that have to be made for adapting Oxalis V4 to persist the incoming messages in an Oracle database and not in the filesystem? Thanks

**Comment by klopojed** [comment]
In oxalis-extension subproject there are two examples of custom modules. We created our own module based on these examples, that sends message to MQ instead of storing to disk

**Comment by rzvpopescu22** [comment]
I will check that. Thanks a lot @klopojed !

**Comment by klopojed** [comment]
Since I've got a question on how we did our own module implementation, in short:

I created our own project that results in jar. The main entry point is InboundModule:

    public class InboundModule extends OxalisModule implements Module {
        @Override
        protected void configure() {
            bindTyped(PayloadPersister.class, OxalisHandler.class);
            bindTyped(ReceiptPersister.class, OxalisHandler.class);
            bindTyped(PersisterHandler.class, OxalisHandler.class);
        }
    }

Then created our own OxalisHandler:

    @Singleton
    @Type("custom")
    public class OxalisHandler implements PersisterHandler {
        // here goes custom code with MQ and whatever
    }

The next I put to resources reference.conf with the following line:

    oxalis.module.custom.inbound.class = x.y.z.InboundModule

And as a last step enabled our OxalisHandler in oxalis.conf:

    oxalis.persister.handler=custom
    oxalis.persister.payload=custom
    oxalis.persister.receipt=custom

That's all. Our jar must be in the classpath

**Comment by open-gdsn** [comment]
Is this 'documentation' still valid for 4.0.4? I do not seem to be able to find any useful documentation on creating peristers, let alone the InboundModule
