### ISSUE TITLE
-d option mandatory in oxalis-standalone for PEPPOL BIS v3 and other EN-16931-derived types

### ISSUE THREAD

**Issue by tjeb** [difi/oxalis#404]
Since UBL version 2.1 is mandated in PEPPOL BIS v3, cbc:UBLVersionID has been removed as an element. Oxalis uses this for value to get to the full document type for the SMP lookup, making it impossible to perform a correct lookup based on in-document information now.

I don't suppose it's possible to make it default to 2.1 (possibly depending on the customizationID, based on the document identifier list)?

**Comment by odha** [comment]
Hi guys,
I just checked. When I use oxalis-outbound, and specify 
<cbc:UBLVersionID>2.1</cbc:UBLVersionID>

as an extra node inside the XML, the XML is succesfully delived, but FAILS validation, because the element cbc:UBLVersionID is not allowed.

cvc-complex-type.2.4.a: Invalid content was found starting with element 'cbc:UBLVersionID'. One of '{"urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2":ProfileExecutionID, "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2":ID}' is expected.
--


So I agree with tjeb, that it's a bug that should perhaps be fixed, because otherwise we can't send PEPPOL BIS v3 files, or SI-UBL 2.0 files wit hOxalsis.

**Comment by odha** [comment]
I now see this issue

https://github.com/difi/oxalis/issues/398
and
https://github.com/difi/oxalis/issues/226

So i guess that means that inspection of the document will stop in the near future and that we need to start building our own SBDH header
