### ISSUE TITLE
test-aksesspunkt.difi.no is down

### ISSUE THREAD

**Issue by pekaaw** [difi/oxalis#468]
This url form the [installation guide](https://github.com/difi/oxalis/blob/master/doc/installation.md) is not working:
<https://test-aksesspunkt.difi.no/transmission/participant/iso6523-actorid-upis::9908:810418052>

Are there any chance it will come up again or is is replaced?

I am working on an api that will generate an EHF Billing Invoice 3.0. We now have a functional generator with and without SBDH and a validator that works with the not-so-new-anymore format.

I would now like to test it through a test accesspoint. Is it possible still?

**Comment by artjomsk** [comment]
I have heard in webinar that test accesspoint is down, because "it's not needed anymore - use OpenPeppol TestBed" and "it's too expensive to support it".

In my opinion, it was useful and contains different functionality comparing to Open Peppol Test Bed.
Difi Test AP page contained all transactions received, required no authorization with certificate, had option to upload file from web.

**Comment by artjomsk** [comment]
Related issue https://github.com/difi/oxalis/issues/429 is Closed

**Comment by klakegg** [comment]
Information related to this:
https://vefa.difi.no/peppol/announcement/2020-01-13-removal-of-access-points-for-testing/

**Comment by pekaaw** [comment]
It sounds like quite a lot of initial work and maintainence to setup an access point that is valid with Open Peppol Test Bed just to send EHF documents.
Before we have used test-aksesspunkt.difi.no to ensure that a validated document actually came through, before deploying new changes to production.

In production we will (very soon) generate a Peppol BIS Billing 3.0 UBL Invoice, use our own validator with updated ruleset and use the Oxalis Outbound component for sending.

Is this considered "best practice", or are there more requirements we should know about?
