### ISSUE TITLE
Missing Oxalis-keystore.jks

### ISSUE THREAD

**Issue by MrKyaw** [difi/oxalis#480]
Dear Contributor,

Pls kindly advise me where can I get the Oxalis-keystore.jks ?
It blocked my learning of Oxalis quite few days.
Hope, some one will help me to speed up to run the application well.

Thanks in advance

**Comment by jannewaren** [comment]
Hello,

Have you read these documents?

https://github.com/difi/oxalis/blob/master/doc/keystore.adoc
This one explains how to get and configure a keystore in Oxalis.

https://peppol.eu/wp-content/uploads/2020/03/How-to-set-up-a-Post-Award-Peppol-Access-Point_v1.5.pdf
This one is more general guide describing the steps you need to take to become a Peppol Access Point.

**Comment by MrKyaw** [comment]
Hi,

Thanks for the prompt reply and I read it.
But not sure without getting or applying the keystore from Peppol.
It will work with Oxalis so Pls kindly advise.

**Comment by jannewaren** [comment]
Sorry but I don't understand what you are trying to achieve. Oxalis does not work without a keystore. You need a keystore to use Oxalis. It is not optional, you really need to have a keystore.

Not to say there couldn't be a way to start the service up with a dummy keystore if you skip some checks, maybe there is but I have no knowledge about this so I can't help. But anyway, to actually send or receive documents you need to get a keystore from Peppol so that's what you should do.

**Comment by MrKyaw** [comment]
Really great thanks for the tip that is must have the keystore from Peppol.
